Grid World Localization
---
Consider a 2 dimensional world, the robot can move only left, right, up, or down. It cannot move diagonally. Also, for this assignment, the robot will never overshoot its destination square; it will either make the movement or it will remain stationary.

**Motions:**
- [0, 0]: no movement
- [0, 1]: move right
- [1, 0]: move down
- [-1, 0]: move up
...

In [1]:
import numpy as np

In [2]:
def init_p():
    nrow, ncol = colors.shape
    p = np.zeros([nrow, ncol])
    for i in range(nrow):
        for j in range(ncol):
            p[i, j] = 1/(nrow*ncol)
    return p

In [3]:
# sense

def sense(p, Z):
    nrow, ncol = colors.shape
    sense_prob =  np.zeros([nrow, ncol])
    for i in range(nrow):
        for j in range(ncol):
            sense_prob[i, j] = sensor_right if colors[i, j] == Z else 1 - sensor_right
    q = p * sense_prob
    # normalization
    q = q/np.sum(q)
    return q

In [4]:
# move

def move(p, U):
    nrow, ncol = p.shape
    q = np.zeros([nrow, ncol])
    for i in range(nrow):
        for j in range(ncol):
            q[i, j] = p_move*p[i-U[0], j-U[1]] + (1-p_move)*p[i, j]
    return q

In [5]:
# combine

def localize(colors, measurements, motions, sensor_right, p_move):
    assert len(measurements) == len(motions)
    
    p = init_p()
    for i in range(len(measurements)):
        measure = measurements[i]
        motion = motions[i]
        
        p = sense(p, measure)
        p = move(p, motion)
    return p

In [6]:
# test

colors = np.array(
         [['G', 'G', 'G'],
          ['G', 'R', 'G'],
          ['G', 'G', 'G']])

measurements = ['R']
motions = [[0, 0]]
sensor_right = 1.0
p_move = 1.0  # probability motion executed correctly

p = localize(colors, measurements, motions, sensor_right, p_move)

print(p)

[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]


In [7]:
colors = np.array(
         [['G', 'G', 'G'],
          ['G', 'R', 'R'],
          ['G', 'G', 'G']])

measurements = ['R']
motions = [[0, 0]]
sensor_right = 0.8
p_move = 1.0  # probability motion executed correctly

p = localize(colors, measurements, motions, sensor_right, p_move)

print(p)

[[0.06666667 0.06666667 0.06666667]
 [0.06666667 0.26666667 0.26666667]
 [0.06666667 0.06666667 0.06666667]]


In [8]:
colors = np.array(
         [['G', 'G', 'G'],
          ['G', 'R', 'R'],
          ['G', 'G', 'G']])

measurements = ['R', 'R']
motions = [[0, 0], [0, 1]]
sensor_right = 0.8
p_move = 0.5

p = localize(colors, measurements, motions, sensor_right, p_move)

print(p)

[[0.02564103 0.02564103 0.02564103]
 [0.21794872 0.21794872 0.41025641]
 [0.02564103 0.02564103 0.02564103]]
